apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 884775304728.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:1.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
